Traceback (most recent call last):
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/main.py", line 34, in <module>
    main()
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/main.py", line 11, in main
    param = load_json(args.config)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/main.py", line 20, in load_json
    param = json.load(data_file)
            ^^^^^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/anaconda3/envs/tllib/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/anaconda3/envs/tllib/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/anaconda3/envs/tllib/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/anaconda3/envs/tllib/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 8 column 5 (char 132)
2024-06-18 19:41:26,235 [trainer.py] => config: exps/FeCAM_cifar100.json
2024-06-18 19:41:26,235 [trainer.py] => prefix: train
2024-06-18 19:41:26,235 [trainer.py] => dataset: cifar100
2024-06-18 19:41:26,235 [trainer.py] => memory_size: 0
2024-06-18 19:41:26,235 [trainer.py] => shuffle: True
2024-06-18 19:41:26,235 [trainer.py] => init_cls: 0
2024-06-18 19:41:26,235 [trainer.py] => increment: 20
2024-06-18 19:41:26,235 [trainer.py] => model_name: fecam
2024-06-18 19:41:26,235 [trainer.py] => convnet_type: resnet18
2024-06-18 19:41:26,235 [trainer.py] => device: [device(type='cuda', index=0), device(type='cuda', index=3)]
2024-06-18 19:41:26,235 [trainer.py] => seed: 1993
2024-06-18 19:41:26,235 [trainer.py] => init_epochs: 200
2024-06-18 19:41:26,235 [trainer.py] => init_lr: 0.1
2024-06-18 19:41:26,235 [trainer.py] => init_weight_decay: 0.0005
2024-06-18 19:41:26,235 [trainer.py] => batch_size: 128
2024-06-18 19:41:26,235 [trainer.py] => num_workers: 8
2024-06-18 19:41:26,235 [trainer.py] => T: 2
2024-06-18 19:41:26,235 [trainer.py] => beta: 0.5
2024-06-18 19:41:26,235 [trainer.py] => alpha1: 1
2024-06-18 19:41:26,235 [trainer.py] => alpha2: 1
2024-06-18 19:41:26,235 [trainer.py] => ncm: False
2024-06-18 19:41:26,235 [trainer.py] => tukey: True
2024-06-18 19:41:26,235 [trainer.py] => diagonal: False
2024-06-18 19:41:26,235 [trainer.py] => per_class: True
2024-06-18 19:41:26,235 [trainer.py] => full_cov: True
2024-06-18 19:41:26,235 [trainer.py] => shrink: True
2024-06-18 19:41:26,235 [trainer.py] => norm_cov: True
Files already downloaded and verified
Files already downloaded and verified
2024-06-18 19:41:27,840 [data_manager.py] => [68, 56, 78, 8, 23, 84, 90, 65, 74, 76, 40, 89, 3, 92, 55, 9, 26, 80, 43, 38, 58, 70, 77, 1, 85, 19, 17, 50, 28, 53, 13, 81, 45, 82, 6, 59, 83, 16, 15, 44, 91, 41, 72, 60, 79, 52, 20, 10, 31, 54, 37, 95, 14, 71, 96, 98, 97, 2, 64, 66, 42, 22, 35, 86, 24, 34, 87, 21, 99, 0, 88, 27, 18, 94, 11, 12, 47, 25, 30, 46, 62, 69, 36, 61, 7, 63, 75, 5, 32, 4, 51, 48, 73, 93, 39, 67, 29, 49, 57, 33]
2024-06-18 19:41:28,064 [fecam.py] => Learning on 0-0
Traceback (most recent call last):
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/main.py", line 34, in <module>
    main()
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/main.py", line 15, in main
    train(args)
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/trainer.py", line 18, in train
    _train(args)
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/trainer.py", line 62, in _train
    model.incremental_train(data_manager)
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/models/fecam.py", line 84, in incremental_train
    train_dataset = data_manager.get_dataset(np.arange(self._known_classes, self._total_classes), source='train',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/imgbreaker/Desktop/FeCAM/FeCAM-main/utils/data_manager.py", line 79, in get_dataset
    data, targets = np.concatenate(data), np.concatenate(targets)
                    ^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 200, in concatenate
ValueError: need at least one array to concatenate
